### ISSUE TITLE
header, pages and navbar

### ISSUE THREAD

**Issue by mve1983** [mve1983/catch-share-capstone-project#2]
As User I want to have a headline with the App name and a option to navigate through the different pages by clicking on the navigate buttons. 

##### Acceptance:
A header with App name and a navbar with navigate options through all different pages.

##### Tasks:
- [x] create Header component
- [x] create Navbar component
- [x] create all initial pages (without content for now)
- [x] Routes for all pages with React Router
- [x] click on navigate button brings user to each page
