### ISSUE TITLE
Map Render + Marker + Places

### ISSUE THREAD

**Issue by mve1983** [mve1983/catch-share-capstone-project#5]
As User I want to see a map on the map page, search for places and set marker on the page.

##### Acceptance:
Map to be shown on Map Page, Search for places possible, marker set possible. 

##### Tasks:
- [x] render map from google api
- [x] search for places with google api
- [x] add a marker to map by clicking
