### ISSUE TITLE
Marker Render on start

### ISSUE THREAD

**Issue by mve1983** [mve1983/catch-share-capstone-project#8]
As User I want to see a map marker for each catch on the Map page.

##### Acceptance:
Map markers on Map page will be shown when page loaded. 

##### Tasks:
- [x] render map markers for all catches
- [x] get all lat/lng coordinates from db data in an array
- [x] delete double lat/lng entries from this array (if more than one catch on same location)
- [x] render markers for each lat/lng coordinate
